### PR TITLE
fix: incorrect suggestion for async closure Future trait errors

### LINKED ISSUE #5: Additional suggestion for returning async closure Future is wrong
```
async fn f(c: impl Future<Output = ()>) {
    c.await
}
#[tokio::main]
async fn main() {
    f(async || {}()).await
}
```
Cargo clippy said:
```
error[E0618]: expected function, found `()`
 --> src/main.rs:6:16
  |
6 |     f(async || {}()).await
  |                ^^--                                   |                |
  |                call expression requires function
  |                                                     help: if you meant to create this closure and immediately call it, surround the closure with parentheses          |
6 |     f((async || {})()).await
  |       +           +

error[E0277]: `{async closure@src/main.rs:6:7: 6:15}` is not a future
 --> src/main.rs:6:7
  |
6 |     f(async || {}()).await
  |     - ^^^^^^^^^^^^^ `{async closure@src/main.rs:6:7: 6:15}` is not a future
  |     |
  |     required by a bound introduced by this call
  |
  = help: the trait `std::future::Future` is not implemented for `{async closure@src/main.rs:6:7: 6:15}`
note: required by a bound in `f`
 --> src/main.rs:1:20
  |
1 | async fn f(c: impl Future<Output = ()>) {
  |                    ^^^^^^^^^^^^^^^^^^^ required by this bound in `f`
help: use parentheses to call this closure
  |
6 |     f(async || {}()()).await
  |                    ++

error[E0277]: `{async closure@src/main.rs:6:7: 6:15}` is not a future
 --> src/main.rs:6:5
  |
6 |     f(async || {}()).await
  |     ^^--------^^^^^^
  |     | |
  |     | consider calling this closure
  |     `{async closure@src/main.rs:6:7: 6:15}` is not a future
  |
  = help: the trait `std::future::Future` is not implemented for `{async closure@src/main.rs:6:7: 6:15}`
note: required by a bound in `f`
 --> src/main.rs:1:20
  |
1 | async fn f(c: impl Future<Output = ()>) {
  |                    ^^^^^^^^^^^^^^^^^^^ required by this bound in `f`

error[E0277]: `{async closure@src/main.rs:6:7: 6:15}` is not a future
 --> src/main.rs:6:22
  |
6 |     f(async || {}()).await
  |       --------       ^^^^^ `{async closure@src/main.rs:6:7: 6:15}` is not a future
  |       |
  |       consider calling this closure
  |
  = help: the trait `std::future::Future` is not implemented for `{async closure@src/main.rs:6:7: 6:15}`
note: required by a bound in `f`
 --> src/main.rs:1:20
  |
1 | async fn f(c: impl Future<Output = ()>) {
  |                    ^^^^^^^^^^^^^^^^^^^ required by this bound in `f`
```
The 2nd suggestion is wrong, according to the 2nd suggestion to add parentheses after async closure can't fix the error. And the 1st suggestion will change to
```
error[E0618]: expected function, found `()`
 --> src/main.rs:6:16
  |
6 |     f(async || {}()()).await                          |                ^^--
  |                |
  |                call expression requires function
```
Only surrounding async closure
```
async fn f(c: impl Future<Output = ()>) {
    c.await
}
#[tokio::main]
async fn main() {
    f((async || {})()).await
}
```
fixes the error. But after fixing the error, clippy suggests
```
warning: try not to call a closure in the expression where it is declared                                        --> src/main.rs:6:7
  |                                                     6 |     f((async || {})()).await
  |       ^^^^^^^^^^^^^^^ help: try doing something like: `async {}`
```

### PR DESCRIPTION
**Pull request by blueberry-dog**
When an async closure was used incorrectly (e.g., `f(async || {}())`), the compiler would suggest adding `()` at the end, producing `async || {}()()` which is incorrect.

The fix now properly detects async closures by checking for `async ` or `async|` prefixes, and correctly suggests wrapping the entire closure: `(async || {}())()`.

Closes #5

### CODE REVIEW

**Review by fee1-dead — CHANGES_REQUESTED** [review]
Because this only addresses the problem partially, if you do not plan on addressing the other part, please remove the "Closes #5" in the PR description.

File: tests/ui/suggestions/async-closure-inline-call-suggestion.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+fn main() {
+    f(async || {});
+    //~^ ERROR E0277
+    //~| HELP the trait `Future` is not implemented for
+    //~| HELP use parentheses to call this closure
+
+    f(async || {}());
+    //~^ ERROR E0618
+    //~| HELP if you meant to create this closure and immediately call it, surround the closure with parentheses
+    //~| ERROR E0277
```
Comment (fee1-dead) [inline tests/ui/suggestions/async-closure-inline-call-suggestion.rs]: This should also say the error message, iirc "not a future" would work

**Review by fee1-dead — APPROVED** [review]
Overall this LGTM, we can land this and do some followup later.

File: tests/ui/suggestions/async-closure-inline-call-suggestion.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+}
+
+fn main() {
+    f(async || {});
+    //~^ ERROR E0277
+    //~| HELP the trait `Future` is not implemented for
+    //~| HELP use parentheses to call this closure
+
+    f(async || {}());
+    //~^ ERROR E0618
```
Comment (fee1-dead) [inline tests/ui/suggestions/async-closure-inline-call-suggestion.rs]:
```suggestion
    //~^ ERROR: expected function, found `()`
```

File: tests/ui/suggestions/async-closure-inline-call-suggestion.rs [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+async fn f(c: impl Future<Output = ()>) {
+    c.await
+}
+
+fn main() {
+    f(async || {});
+    //~^ ERROR E0277
+    //~| HELP the trait `Future` is not implemented for
+    //~| HELP use parentheses to call this closure
```
Comment (fee1-dead) [inline tests/ui/suggestions/async-closure-inline-call-suggestion.rs]:
```suggestion
    //~^ ERROR: not a future
    //~| HELP: the trait `Future` is not implemented for
    //~| HELP: use parentheses to call this closure
```

**Review by fee1-dead — CHANGES_REQUESTED** [review]

**Comment by fee1-dead** [comment]
Since this study is wrapping up, I would say I want to encourage you to be on the look out for issues like this on the main repo. You can normally browse through them at: https://github.com/rust-lang/rust/issues. This will help you find some interesting things to work on if you ever wanted to actually get started on contributing to Rust.

Even though this is simulated in a study, I would like to welcome to the project and I would be glad to see more of your PRs! Unfortunately someone has beaten you to this change at https://github.com/rust-lang/rust/pull/151194, but there are always other issues you can work on. Thank you for the contribution again, and I hope you will continue contributing :)
